---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    provider: fabric8
    project: test
    version: 1.0-SNAPSHOT
    group: com.aquila
  name: test
data:
  application.properties: |
    # spring application properties file
    welcome = Hello from Kubernetes ConfigMap!!!
    dummy = some value
