---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    expose: "true"
    provider: fabric8
    project: test
    version: 1.0-SNAPSHOT
    group: com.aquila
  name: test
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    project: test
    provider: fabric8
    group: com.aquila
