metadata:
  annotations:
    configmap.fabric8.io/update-on-change: test
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: config
          configMap:
            name: test
            items:
            - key: application.properties
              path: application.properties
      containers:
        - volumeMounts:
            - name: config
              mountPath: /deployments/config
